//
//  PolaroidCameraViewController.swift
//  Good mood Camera
//
//  Created by Stanley Tseng on 2019/12/9.
//  Copyright © 2019 StanleyAppWorld. All rights reserved.
//
//  Camera程式碼參考自APPCODA Simon版本
//  預計還要增加拍照後顯示照片在該頁面上，以及可開啟相簿，以上功能尚未製作。
//  鏡頭方向自動修正未解決（有找到相關程式碼，但還需要測試）

import UIKit
import Photos

class PolaroidCameraViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    
    //Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    //Allows the user to put the camera in photo mode.
    @IBOutlet fileprivate var photoModeButton: UIButton!
    @IBOutlet fileprivate var toggleCameraButton: UIButton!
    @IBOutlet fileprivate var toggleFlashButton: UIButton!
    
    //Allows the user to put the camera in video mode.
    @IBOutlet fileprivate var videoModeButton: UIButton!
    
    @IBOutlet var showImg: UIImageView! // 測試秀出拍的照片用
    
//    var previewLayer: AVCaptureVideoPreviewLayer? // 測試修正鏡頭方向用
    let cameraController = CameraController()
    
}

extension PolaroidCameraViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // 測試秀出拍的照片用
        showImg = UIImageView(frame: CGRect(
            x: self.view.frame.minX + 100, y: self.view.frame.maxY - 200, width: 150, height: 150))
        self.view.addSubview(showImg)
        
        
        func configureCameraController() {
            
            cameraController.prepare {(error) in
                if let error = error {
                    print(error)
                }
                try? self.cameraController.displayPreview(on: self.capturePreviewView)
            }
        }
        
        func styleCaptureButton() {
            captureButton.layer.borderColor = UIColor.black.cgColor
            captureButton.layer.borderWidth = 2
            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
        }
        
        styleCaptureButton()
        configureCameraController()
    }
}
    
extension PolaroidCameraViewController {
    // 設定閃光燈開關功能
    @IBAction func toggleFlash(_ sender: UIButton) {
        if cameraController.flashMode == .on {
            cameraController.flashMode = .off
            toggleFlashButton.setImage(UIImage(named: "Flash off"), for: .normal)
        }
        
        else {
            cameraController.flashMode = .on
            toggleFlashButton.setImage(UIImage(named: "Flash on"), for: .normal)
        }
    }
    
    // 切換相機前後鏡頭
    @IBAction func switchCameras(_ sender: UIButton) {
        do {
            try cameraController.switchCameras()
        }
        catch {
            print(error)
        }
        
        switch cameraController.currentCameraPosition {
        case .some(.front):
            toggleCameraButton.setImage(UIImage(systemName: "camera.rotate"), for: .normal)
        case .some(.rear):
            toggleCameraButton.setImage(UIImage(systemName: "camera.rotate.fill"), for: .normal)
            
        case .none:
            return
        }
    }
    
    // 呼叫Camera Controller內的captureImage方法來擷取相片
    @IBAction func captureImage(_ sender: UIButton) {
        cameraController.captureImage {(image, error) in
            guard let image = image else {
                print(error ?? "Image capture error")
                return
            }
            // 使用PHPhotoLibary類別來儲存圖片到內置的相片資料庫
            try? PHPhotoLibrary.shared().performChangesAndWait {
                PHAssetChangeRequest.creationRequestForAsset(from: image)
                
                // 測試是否可以秀出拍的照片
                
                self.showImg.image = image
                self.showImg.contentMode = .scaleAspectFill
                
                
            }
        }
    }
}
